### PR TITLE
Accesibility support

### PR DESCRIPTION
**Pull request by JLHwung**
Added accessibility support according to

- https://www.w3.org/TR/html-aria/
- https://v4-alpha.getbootstrap.com/getting-started/accessibility

The *skip to main content* feature introduces an extra banner for sighted keyboard users who press `enter` key to navigate the website.

<figure>
<caption>screenshot</caption>
screen shot 2016-12-17 at 01 15 33
</figure>

I find that PO seems to freeze features after I go through the *closed* pull requests. I will leave PO to decide on this pull request.

Should this repository not maintained anymore, please state the policy clearly.

Edits: Added new knowledge on contribution policy.

### CODE REVIEW

**Comment by pinggod** [comment]
Do this in your fored repository.

**Comment by JLHwung** [comment]
Personally I am disappointed that this feature is not merged as there is not any visual difference for normal users while it does offer convenience for sighted users.
Anyway, please state feature policy on `readme.md`. Good for potential contributors.

**Comment by pinggod** [comment]
Thanks for your good job,  and I will add it.

**Comment by JLHwung** [comment]
You are very welcome.

**Pull request closed without merging**
